version: '3.2'
services:
  legacy-db:
    build: legacy-db
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./legacy-db
        target: /docker-entrypoint-initdb.d
  zookeeper:
    image: debezium/zookeeper:0.7
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:0.7
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper
  connect:
    image: debezium/connect:0.7
    ports:
      - 8083:8083
    links:
      - zookeeper
      - kafka
      - legacy-db
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - BOOTSTRAP_SERVERS=kafka:9092