version: '3.2'
services:
  legacy-db:
    build: legacy-db
    ports:
      - 5432:5432
  zookeeper:
    image: debezium/zookeeper:0.7
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:0.7
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    ports:
      - 9200:9200
    environment:
      - xpack.security.authc.anonymous.roles=superuser
  connect:
    image: debezium/connect:0.7
    ports:
      - 8083:8083
    links:
      - zookeeper
      - kafka
      - legacy-db
      - elasticsearch
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - type: bind
        source: ./connectors
        target: /kafka/connect/elasticsearch
  build-kafka-connect-elasticsearch:
    build: build-kafka-connect-elasticsearch
    volumes:
      - type: bind
        source: ./connectors/elasticsearch
        target: /build
    environment:
      - MAVEN_CONFIG=/home/maven/.m2